spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 465
    username: fawez
    password: fawez
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        ssl:
          enable: true
          trust: "*"
        starttls:
          enabled: true
    protocol:  smtp

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/book-social-network"

application:
#  security:
#    jwt:
#      secret-key: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTcyMDcwMDE4MywiaWF0IjoxNzIwNzAwMTgzfQ.l4imijJhybizVPkpVtk1nXRqhmBGekkzLkrjKcld6Bs
#      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  cors:
    origins: http://193.70.33.77:8088/,http://localhost:8088/,http://localhost:4200,http://193.70.33.77:8080
  file:
    uploads:
      photos-output-path: ./uploads
server:
  port: 8088